[2025-09-09T13:01:08.336+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_pipeline.run_dbt_models manual__2025-09-09T12:56:06.105052+00:00 [queued]>
[2025-09-09T13:01:08.340+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_pipeline.run_dbt_models manual__2025-09-09T12:56:06.105052+00:00 [queued]>
[2025-09-09T13:01:08.340+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-09-09T13:01:08.346+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-09-09 12:56:06.105052+00:00
[2025-09-09T13:01:08.350+0000] {standard_task_runner.py:57} INFO - Started process 257 to run task
[2025-09-09T13:01:08.352+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_pipeline', 'run_dbt_models', 'manual__2025-09-09T12:56:06.105052+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dbt_workflow_dag.py', '--cfg-path', '/tmp/tmpm6eb1c8n']
[2025-09-09T13:01:08.354+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask run_dbt_models
[2025-09-09T13:01:08.362+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-09T13:01:08.382+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_pipeline.run_dbt_models manual__2025-09-09T12:56:06.105052+00:00 [running]> on host 882ca7530331
[2025-09-09T13:01:08.432+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-09T12:56:06.105052+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-09T12:56:06.105052+00:00'
[2025-09-09T13:01:08.433+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-09T13:01:08.433+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /usr/app/itsm_dbt_project && dbt run']
[2025-09-09T13:01:08.438+0000] {subprocess.py:86} INFO - Output:
[2025-09-09T13:01:08.440+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /usr/app/itsm_dbt_project: No such file or directory
[2025-09-09T13:01:08.440+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-09T13:01:08.446+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-09T13:01:08.447+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dbt_pipeline, task_id=run_dbt_models, execution_date=20250909T125606, start_date=20250909T130108, end_date=20250909T130108
[2025-09-09T13:01:08.453+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 1.; 257)
[2025-09-09T13:01:08.493+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-09T13:01:08.506+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
