[2025-09-09T12:56:06.970+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_pipeline.run_dbt_models manual__2025-09-09T12:56:06.105052+00:00 [queued]>
[2025-09-09T12:56:06.973+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_pipeline.run_dbt_models manual__2025-09-09T12:56:06.105052+00:00 [queued]>
[2025-09-09T12:56:06.973+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-09-09T12:56:06.979+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-09-09 12:56:06.105052+00:00
[2025-09-09T12:56:06.981+0000] {standard_task_runner.py:57} INFO - Started process 775 to run task
[2025-09-09T12:56:06.983+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_pipeline', 'run_dbt_models', 'manual__2025-09-09T12:56:06.105052+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dbt_workflow_dag.py', '--cfg-path', '/tmp/tmp0wvq0emw']
[2025-09-09T12:56:06.984+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask run_dbt_models
[2025-09-09T12:56:06.993+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-09T12:56:07.016+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_pipeline.run_dbt_models manual__2025-09-09T12:56:06.105052+00:00 [running]> on host e89ef2e1ef82
[2025-09-09T12:56:07.059+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-09-09T12:56:06.105052+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-09T12:56:06.105052+00:00'
[2025-09-09T12:56:07.059+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-09T12:56:07.060+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /usr/app/itsm_dbt_project && dbt run']
[2025-09-09T12:56:07.063+0000] {subprocess.py:86} INFO - Output:
[2025-09-09T12:56:07.065+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /usr/app/itsm_dbt_project: No such file or directory
[2025-09-09T12:56:07.065+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-09-09T12:56:07.072+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-09T12:56:07.073+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_pipeline, task_id=run_dbt_models, execution_date=20250909T125606, start_date=20250909T125606, end_date=20250909T125607
[2025-09-09T12:56:07.081+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 1.; 775)
[2025-09-09T12:56:07.124+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-09T12:56:07.137+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
